[package]
name = "rocket"
version = "0.1.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>"]
build = "build.rs"

[dependencies]
itertools = "0.3"
piston = "0.10"
piston2d-graphics = "0.9"
pistoncore-glutin_window = "0.12"
piston2d-opengl_graphics = "0.12"
rand = "0.3"
