[package]
name = "rocket"
version = "0.1.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>"]
build = "build.rs"

[dependencies]
itertools = "0.4.8"
piston = "0.17"
piston_window = "0.34"
piston2d-graphics = "0.13"
piston2d-opengl_graphics = "0.23"
rand = "0.3"
pistoncore-sdl2_window = "*"