[package]
name = "rocket"
version = "1.0.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>"]
build = "build.rs"

[dependencies]
itertools-num = "0.1.1"
piston_window = "0.63.0"
piston2d-opengl_graphics = "0.39.0"
rand = "0.3.14"
