[package]
name = "rocket"
version = "0.2.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>"]
build = "build.rs"

[dependencies]
itertools = "0.4.13"
piston = "0.22.0"
piston_window = "0.45.0"
piston2d-graphics = "0.16.0"
piston2d-opengl_graphics = "0.28.2"
rand = "0.3.14"
pistoncore-sdl2_window = "0.30.0"
