[package]
name = "rocket"
version = "0.2.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>"]
build = "build.rs"

[dependencies]
itertools = "0.4.19"
piston = "0.27.0"
piston_window = "0.58.0"
piston2d-graphics = "0.19.0"
piston2d-opengl_graphics = "0.36.1"
rand = "0.3.14"
